# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37c265a2a2789bd43467e056bc492638127f9955037f427d9e9bddf38dfce6138780938fae257b05ecabe57c531f7bd8dbb40099b04cda2ab2146bf3a068058f

test:
  secret_key_base: 6d6d06ba00e995e02ea512b6a8ab600cbd4a8df1dad600f9c452c51b85259b60dac59e9ad35a158220662f41aa5bb1a4b9b84beae438c9cc6148410c3ff34b0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
